### ISSUE TITLE
[Documentation] Opening Node.js installation docs redirects me to a login page

### ISSUE THREAD

**Issue by tasgon** [hyperdxio/hyperdx#19]
I'm trying to read the Node.js docs at https://www.hyperdx.io/docs/install/javascript, but once I open that link, I'm immediately moved to https://www.hyperdx.io/login.

Not sure if this issue belongs here, but I couldn't find another relevant repo to open it in.

**Comment by MikeShi42** [comment]
Thank you for reporting that! Definitely a bug, will get the fix deployed shortly, really apologize for that - docs should not be auth walled!

In the meanwhile - you can check out the NPM docs as well which should be pretty similar https://www.npmjs.com/package/@hyperdx/node-opentelemetry

**Comment by MikeShi42** [comment]
@tasgon - this should be fixed and in production now, thanks again for reporting this issue and apologies for that! I'll go ahead and close this issue, let me know if you see any other weirdness :)

**Comment by tasgon** [comment]
The issue doesn't appear to be resolved for me. I'm still getting redirected on both Firefox and Chrome.

**Comment by MikeShi42** [comment]
@tasgon you're right... super sorry about that, I must have tested it while accidentally logged in to incognito 🤦‍♂️ 

I'll be pushing a fix shortly and will leave it open till you can confirm so I don't make that mistake again!

**Comment by MikeShi42** [comment]
@tasgon - just pushed another fix, let me know if it looks better now!

**Comment by tasgon** [comment]
Looks like it works now, thank you!
